### ISSUE TITLE
import of C++ module 'CoreGraphics' appears within extern "C" language linkage specification

### ISSUE THREAD

**Issue by vieri68** [adamwulf/ClippingBezier#33]
On Xcode15, import of C++ module 'CoreGraphics' appears within extern "C" language linkage specification

**Comment by Litome** [comment]
This is a duplicate of this issues: https://github.com/adamwulf/ClippingBezier/issues/31
Which is fixed but there hasn't been releases cut for Cocoapods etc... yet I don't think.

@adamwulf Do you think you could create a release containing the fix for the different package delivery mechanisms please? Or is that something we can help with?

**Comment by adamwulf** [comment]
I've just pushed up 1.2.4 that includes the necessary version bump in the `podspec` file, and i've also pushed to cocoapods too, so everything should be good to go. lmk if you run into issues, thanks!

**Comment by vieri68** [comment]
thanks! 🎉
